### PR TITLE
Master server synchronisation

### PR DESCRIPTION
**Pull request by barnabwhy**
Adds scalability to the master server by allowing a list of other master server instances to share data with and to use for synchronisation when the server starts up.

- JSON config
- Password protected and restricts to known IPs
- Can work just on its own if instances.json is empty or contains only itself
- Syncs servers and accounts on startup, prioritising more recent account data (although this edge case shouldn't be needed hopefully)
- Broadcasts changes to servers and accounts to all known instances
- Creates backups of playerdata.db in case of catastrophic failure and/or accidental overwrites.
- Allows for hot-connecting of instances by virtue of how it works. Just needs every instance to agree on which hosts are allowed to access instancing enpoints

### CODE REVIEW

**Comment by barnabwhy** [comment]
**testAddServer.js** is not at all needed
**upgradeTableTimestamps.js** is only needed once ever to add the lastModified colum to the accounts database. it defaults all timestamps to 0 cause the past < the present and 0 < the present, what could go wrong

**Comment by barnabwhy** [comment]
## TODO:
**Implementation:**
- [ ] Add timestamps to broadcast messages
- [ ] Add timestamps to sync responses
- [ ] Add lastModified to GameServer class
----
**Testing:**
- [ ] Test ability for client to switch dynamically
- [ ] Test scalability (may need help from others), try up to 5 instances and 5 servers with also some number of dummy servers + up to 25 players
- [ ] Investigate data integrity at scale
----
**Polish:**
- [ ] Comments with explanations of everything
- [ ] Clean up unneeded files and functions
- [ ] Prepare for release

**Comment by emma-miler** [comment]
Authentication and synchronisation code seems stable, and shouldn't really be affected by scaling.
Current objectives:

### Internals

- [ ] Fix authentication to game servers registered to another master server
- [x] Make mainmenupromos pulled from server
- [ ] Add automatic game server rollover on server failure (needs game server code too)
- [x] Add proper logging (sort of done)

### Externals
- [ ] Add data extraction for use in dashboard
- [ ] Add dashboard
- [ ] Integration with alert system?

### Testing

- [ ] Run multi-instance public test (5-10 instances)

**Comment by barnabwhy** [comment]
this plan looks good to me, everything here good with you @BobTheBob9?

**Comment by barnabwhy** [comment]
> * [x]  Fix authentication to game servers registered to another master server
My last two commits fixed this issue

**Comment by barnabwhy** [comment]
Honestly might be ready to ship in its current state, no breaking changes have been pushed since we did a larger scale test and the last internal todo is sorted as of my commits which fixed the authentication error mentioned prior.

**Comment by barnabwhy** [comment]
Gonna mark as ready for review

**Comment by barnabwhy** [comment]
Okay like actually all good now i think

**Pull request closed without merging**
