### PR TITLE
Block incorrect hostname

### PR DESCRIPTION
**Pull request by barnabwhy**
EXPECTED_HOST env var
e.g. `EXPECTED_HOST=northstar.tf`

### CODE REVIEW

**Comment by pg9182** [comment]
I'd probably limit this to the server registration/heartbeat endpoints, and also check that the CF-Worker header isn't set too.

**Review by pg9182 — COMMENTED** [review]
I'd probably limit this to the server registration/heartbeat endpoints, and also check that the CF-Worker header isn't set too.

**Comment by GeckoEidechse** [comment]
> I'd probably limit this to the server registration/heartbeat endpoints

Any reason why only limit to those?

**Comment by pg9182** [comment]
Superseded by [R2Northstar/Atlas](https://github.com/R2Northstar/Atlas/blob/0cec719bf38ce61f9176b2cf5094c5e7e8f0529b/pkg/atlas/config.go#L36-L38).

**Pull request closed without merging**
