### PR TITLE
Added 404 page

### PR DESCRIPTION
**Pull request by taskinoz**
Thought it might be better than having a raw json error

image

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Noice :D

The only potential that comes to mind is that Internet background noise scanning random pages will hit 404s a lot which will also trigger downloading the video. Given however that video is cached on CloudFlare edge that's probably not gonna be an issue ^^

@barnabwhy wanna maybe take a look and leave review so I can merge it?

**Comment by barnabwhy** [comment]
@GeckoEidechse it should be fine given it's cached and the status code is set. Any non-humans that encounter 404 tend to not attempt to render the web page

**Comment by taskinoz** [comment]
I could look at making it much smaller and just having an image or svg instead of a video

**Comment by GeckoEidechse** [comment]
> I could look at making it much smaller and just having an image or svg instead of a video

Nah, it's fine. As barnaby said, it's likely not an issue. We'll just test in prod and if we start noticing issues with MS, we just revert and go for lower bandwidth solution ^^

**Comment by pg9182** [comment]
If you are planning to continue working on this, it needs to be re-submitted against [R2Northstar/NorthstarTF](https://github.com/R2Northstar/NorthstarTF) and [R2Northstar/Atlas](https://github.com/R2Northstar/Atlas).

**Pull request closed without merging**
