### PR TITLE
Added basic functionalities for player bans from masterserver

### PR DESCRIPTION
**Pull request by wolf109909**
changed database structure, 
do this to the player database to make it actually work:
alter table accounts ADD isBanned INTEGER DEFAULT 0;
running this with an unmodified database should have no conflict however, due to isBanned will only trigger auth error when it is exactly "1".

### CODE REVIEW

**Comment by wolf109909** [comment]
Currently, the only way to actually ban someone is to directly connect to the database and modify the ''isBanned' value for each player. but I have made some functions left in there for direct banning and unbanning from within the js. not called by anything atm

**Comment by wolf109909** [comment]
found some deadly dead bug, closing for now

**Comment by wolf109909** [comment]
fixed the deadly dead issue and its working on my side now

**Comment by wolf109909** [comment]
fixed the bugs that stop this from working. the reason is I'm too lazy to upload my code that's running fine up here and just made the changes by editing the code on github. made tons of typos and now this should work as intended.

**Comment by pg9182** [comment]
We are not currently planning to implement master server bans, but we may revisit this in the future if necessary.

**Pull request closed without merging**
