### PR TITLE
add index support and iterate tables

### PR DESCRIPTION
**Pull request by barnabwhy**
should make the /account/lookup_uid route return faster because now it indexes the username column

### CODE REVIEW

**Comment by barnabwhy** [comment]
(yes i misspelled indices)

**Comment by GeckoEidechse** [comment]
Given that the slow response time acted like an artificial rate limit, we should maybe also add a ratelimit with this PR just so someone (ab)using this to get a lot of UID<->username mappings doesn't get the Origin account used to make this work ratelimited on EA's side.

**Comment by barnabwhy** [comment]
> Given that the slow response time acted like an artificial rate limit, we should maybe also add a ratelimit with this PR just so someone (ab)using this to get a lot of UID<->username mappings doesn't get the Origin account used to make this work ratelimited on EA's side.

this works by querying our db, hence why indices are good. it won't ever request to origin from this endpoint. and it should already be ratelimited

**Comment by pg9182** [comment]
Superseded by [R2Northstar/Atlas](https://github.com/R2Northstar/Atlas/blob/0cec719bf38ce61f9176b2cf5094c5e7e8f0529b/db/atlasdb/001_init_db.go#L15-L33).

Regarding indexes, I got significant improvements from an index on `(username, uid)` (both means that it takes a little bit more space, but doesn't need to access the table to get the uid once it finds the username since both are in the index) while also increasing the DB page cache size (so more stays in memory) and enabling WAL (to reduce blocking).

**Pull request closed without merging**
