### PR TITLE
Encode usernames so that they are valid URI strings

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Some users were failing auth due to their name not being a valid URI string, namely "Gromit      " (6 spaces) ended up being shortened to "Gromit" and therefore was failing auth

This could use some testing, idk how to test this particular case properly tbh

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Huh, so I've seen them playing on Northstar a few weeks before so I'm wondering what we changed that caused it to break for them ^^

@barnabwhy any ideas? Wanna take a look at the PR? <3

**Comment by barnabwhy** [comment]
Talking to Spoon on the discord about this right now. We assume that there's some error in the request that goes to gameservers from masterserver if there are spaces in the username

**Review by barnabwhy — APPROVED** [review]
Lgtm. Spoon tested here (https://discord.com/channels/920776187884732556/936105663942246410/972819135190937600) and it works so it should be fine to merge as it just fixes the error cause by unescaped chars and the gameserver decodes it fine

**Comment by ASpoonPlaysGames** [comment]
https://github.com/R2Northstar/NorthstarMasterServer/commit/737c637c9f4e9708eab3d8430a908dd5e549d689
looks like this commit is what changed it, but it seems the masterserver itself wasnt updated until recently? (Gromit says it stopped working on the 3rd, so maybe the 1.7.0 update and they just didn't play until the 3rd or something?)

**Comment by barnabwhy** [comment]
> https://github.com/R2Northstar/NorthstarMasterServer/commit/737c637c9f4e9708eab3d8430a908dd5e549d689
> looks like this commit is what changed it, but it seems the masterserver itself wasnt updated until recently? (Gromit says it stopped working on the 3rd, so maybe the 1.7.0 update and they just didn't play until the 3rd or something?)

Yeah ms wasn't updated until recently. We got the origin dtuff working around the 3rd

**Pull request merged**
