### PR TITLE
Web landing page

### PR DESCRIPTION
**Pull request by barnabwhy**
Adds a landing page at https://northstar.tf/ (see screenshot).
Background video isn't final, Smurfson has offered to make one so that we don't have to use a poorly cut version of the gameplay trailer.
Download button downloads the latest release from github and if it fails to find the download url, just goes to the page of the latest release. this means that the site can work without js but works a little better with it (js off will also make the top link bar not fade in when you scroll)
Any thoughts just ping me on discord.

(also moves github redirect to https://northstar.tf/github so that it still exists)

image

### CODE REVIEW

**Comment by barnabwhy** [comment]
Opened as a draft because the background video isn't final

**Comment by barnabwhy** [comment]
Also works on small screens and bigger screens quite well although somewhat not as well as on 1080p

Emualated 4k: (just zoomed out to 50% on 1080p)


Emulated iPhone 11 Pro (using dev tools to replicate screen size):


Actual iPhone 7: (can't take full page screenshot)

**Comment by barnabwhy** [comment]
I reckon this is good to go now

**Comment by barnabwhy** [comment]
Screenshots updated to reflect added page content

**Comment by GeckoEidechse** [comment]
Looks awesome :D

**Review by abarichello — APPROVED** [review]
Thanks!

**Pull request merged**
