### PR TITLE
uid<->username lookup

### PR DESCRIPTION
**Pull request by barnabwhy**
Relies on #42

Adds lookup endpoints for getting uid by username or username by uid.

### CODE REVIEW

**Review by abarichello — APPROVED** [review]
thank

**Comment by abarichello** [comment]
@barnabwhy had some problems running this on node 17.8 but it works on 17.7
image

**Comment by barnabwhy** [comment]
> @barnabwhy had some problems running this on node 17.8 but it works on 17.7
> image

the code that failed is already on master, i was just noting that it seems my install of node or maybe just openssl doesn’t like making requests to origin

**Comment by abarichello** [comment]
I should also note that using email/pwd login gave me some errors due to an email confirmation popup, I had to config the cookie sid file

**Pull request merged**
