### PR TITLE
Query game port on server create

### PR DESCRIPTION
**Pull request by barnabwhy**
Seems to work okay with real game servers

### CODE REVIEW

**Comment by barnabwhy** [comment]
(I stole code from r5r so it should work great

**Comment by barnabwhy** [comment]
Second commit isn't what it says. I just added a comment to the encryption key line. But github desktop decided to keep my commit message from another branch

**Comment by GeckoEidechse** [comment]
Live on MR, so should be fine to merge.

**Comment by GeckoEidechse** [comment]
Would in theory break registration if we ever mess with encryption key.

**Pull request merged**
