### PR TITLE
POST /client/get_server_address

### PR DESCRIPTION
**Pull request by barnabwhy**
Adds the ability for servers' addresses to be sent to the client independent of authenticating with them so that the client can check the ping of the server.

Can be used to get server ping without adding much stress to game servers.

### CODE REVIEW

**Comment by MiloAkerman** [comment]
Wouldn't this pose a security risk? If the data is intercepted the servers would be exposed

**Comment by BobTheBob9** [comment]
not 100% certain if i want to do this, it's a fair request but i think something like [this](https://github.com/R2Northstar/Northstar/issues/41) might be able to do the same thing without giving incredibly easy access to ips
while i get the barrier to get them is still low, might be easier not to in this case

**Comment by pg9182** [comment]
I agree with Bob about this. In addition to general security, keeping IPs gated by the master server also allows things like global rate-limiting and blacklisting if it ever becomes necessary.

The other possibility would be to store reported ping values from clients, cluster by region, remove outliers, take the average (or possibly just do percentiles assuming people will know how to read them), then show those as ping estimates.

**Comment by barnabwhy** [comment]
The idea with this was that it still needs the same inputs from the client to make this request, since it is just copied code from authenticate with server, and as a result changes nothing other than allowing clients to get ips in a manner which will cause less strain on game servers by not sending the authentication request to the game server from the master server.

**Comment by MiloAkerman** [comment]
@BobTheBob9 if this is true then don't we already have a huge security flaw during authentication? Since auth doesn't need an accurate ping then there's also the possibility of having the client message the master server, which then messages the individual server to auth.

**Comment by BobTheBob9** [comment]
> @BobTheBob9 if this is true then don't we already have a huge security flaw during authentication? Since auth doesn't need an accurate ping then there's also the possibility of having the client message the master server, which then messages the individual server to auth.

this is the way auth already works

**Comment by barnabwhy** [comment]
**Alternative idea:**
Instead of using the `/client/get_server_address` POST request, have a `/client/servers_with_addresses` GET request which still requires authentication but instead of requiring individual requests, sends the server list + any public servers' IP addresses.
[https://github.com/barnabwhy/NorthstarMasterServer/tree/alternative-proposal](https://github.com/barnabwhy/NorthstarMasterServer/tree/alternative-proposal)

**Comment by barnabwhy** [comment]
I have just realised how bad of an idea this actually is and as a result I am closing this PR and have opened a new one with resource-intensive code (#9).

**Problems:**
1. As this is meant to be used for getting server ping and the client would in an ideal scenario be able to ping every server. This means that with *n* servers and *m* clients concurrently fetching the server list, they would send *m(n+1)* requests; probably causing serious slow-downs to all clients requests to the masterserver.
2. Ports are also sent alongside the IPs which is not so good given that would allow a bad actor to easily flood the game server with requests.

**Pull request closed without merging**
