### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by emma-miler**

### CODE REVIEW

**Review by GeckoEidechse — APPROVED** [review]
No clue why we haven't merged this yet. Deprecation notice and pointing to Atlas should have been up since Atlas deployment ^^

**Comment by Alystrasz** [comment]
@GeckoEidechse you should also archive this repository: https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

This will make a banner appear on all associated webpages: 

image

**Comment by GeckoEidechse** [comment]
I think that's planned but we want close/move all remaining issues and PRs first because AFAIK you cannot interact with them any more once archived ^^

**Comment by pg9182** [comment]
Now that we've finished regions, all that's left is the bad words list and invite handling. The former doesn't have any important discussions, and the latter is very simple (and not even fully implemented elsewhere yet). I think it's safe to archive this now if you want @GeckoEidechse.

Only thing we might want to do first is finish atlas docs.

**Pull request merged**
